tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "chezmoi"
brew "fzf"
brew "maven"
brew "neovim"
brew "node"
brew "python@3.9"
brew "ruby", link: true
brew "starship"
brew "subversion"
cask "font-cascadia-code"
cask "iterm2"
cask "maccy"
cask "scroll-reverser"
cask "iina"

