tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "chezmoi"
brew "fzf"
brew "neovim"
brew "starship"
cask "font-cascadia-code"
cask "iterm2"
cask "maccy"
cask "scroll-reverser"
cask "iina"

