[keyboard]
# https://alacritty.org/config-alacritty-bindings.html
bindings = [
    # go word back / forward
    { key = "ArrowLeft", mods = "Alt", chars = "\u001BB" },
    { key = "ArrowRight", mods = "Alt", chars = "\u001BF" },
    # go line beginning / end
    { key = "ArrowLeft", mods = "Command", chars = "\u0001" },
    { key = "ArrowRight", mods = "Command", chars = "\u0005" },
    # { key = "Paste", action = "Paste" },
    # { key = "Copy", action = "Copy" },
    # { key = "L", mods = "Control", action = "ClearLogNotice" },
    # { key = "L", mods = "Control", chars = "\f" },
    # { key = "Home", mods = "Alt", chars = "\u001B[1;3H" },
    # { key = "Home", mode = "AppCursor", chars = "\u001BOH" },
    # { key = "Home", mode = "~AppCursor", chars = "\u001B[H" },
    # { key = "End", mods = "Alt", chars = "\u001B[1;3F" },
    # { key = "End", mode = "AppCursor", chars = "\u001BOF" },
    # { key = "End", mode = "~AppCursor", chars = "\u001B[F" },
    # { key = "PageUp", mode = "~Alt", mods = "Shift", action = "ScrollPageUp" },
    # { key = "PageUp", mode = "Alt", mods = "Shift", chars = "\u001B[5;2~" },
    # { key = "PageUp", mods = "Control", chars = "\u001B[5;5~" },
    # { key = "PageUp", mods = "Alt", chars = "\u001B[5;3~" },
    # { key = "PageUp", chars = "\u001B[5~" },
    # { key = "PageDown", mode = "~Alt", mods = "Shift", action = "ScrollPageDown" },
    # { key = "PageDown", mode = "Alt", mods = "Shift", chars = "\u001B[6;2~" },
    # { key = "PageDown", mods = "Control", chars = "\u001B[6;5~" },
    # { key = "PageDown", mods = "Alt", chars = "\u001B[6;3~" },
    # { key = "PageDown", chars = "\u001B[6~" },
    # { key = "Tab", mods = "Shift", chars = "\u001B[Z" },
    # { key = "Back", chars = "\u007F" },
    # { key = "Back", mods = "Alt", chars = "\u001B\u007F" },
    # { key = "Insert", chars = "\u001B[2~" },
    # { key = "Delete", chars = "\u001B[3~" },
    # { key = "Left", mods = "Shift", chars = "\u001B[1;2D" },
    # { key = "Left", mods = "Control", chars = "\u001B[1;5D" },
    # { key = "Left", mods = "Alt", chars = "\u001B[1;3D" },
    # { key = "Left", mode = "~AppCursor", chars = "\u001B[D" },
    # { key = "Left", mode = "AppCursor", chars = "\u001BOD" },
    # { key = "Right", mods = "Shift", chars = "\u001B[1;2C" },
    # { key = "Right", mods = "Control", chars = "\u001B[1;5C" },
    # { key = "Right", mods = "Alt", chars = "\u001B[1;3C" },
    # { key = "Right", mode = "~AppCursor", chars = "\u001B[C" },
    # { key = "Right", mode = "AppCursor", chars = "\u001BOC" },
    # { key = "Up", mods = "Shift", chars = "\u001B[1;2A" },
    # { key = "Up", mods = "Control", chars = "\u001B[1;5A" },
    # { key = "Up", mods = "Alt", chars = "\u001B[1;3A" },
    # { key = "Up", mode = "~AppCursor", chars = "\u001B[A" },
    # { key = "Up", mode = "AppCursor", chars = "\u001BOA" },
    # { key = "Down", mods = "Shift", chars = "\u001B[1;2B" },
    # { key = "Down", mods = "Control", chars = "\u001B[1;5B" },
    # { key = "Down", mods = "Alt", chars = "\u001B[1;3B" },
    # { key = "Down", mode = "~AppCursor", chars = "\u001B[B" },
    # { key = "Down", mode = "AppCursor", chars = "\u001BOB" },
    # { key = "F1", chars = "\u001BOP" },
    # { key = "F2", chars = "\u001BOQ" },
    # { key = "F3", chars = "\u001BOR" },
    # { key = "F4", chars = "\u001BOS" },
    # { key = "F5", chars = "\u001B[15~" },
    # { key = "F6", chars = "\u001B[17~" },
    # { key = "F7", chars = "\u001B[18~" },
    # { key = "F8", chars = "\u001B[19~" },
    # { key = "F9", chars = "\u001B[20~" },
    # { key = "F10", chars = "\u001B[21~" },
    # { key = "F11", chars = "\u001B[23~" },
    # { key = "F12", chars = "\u001B[24~" },
    # { key = "F1", mods = "Shift", chars = "\u001B[1;2P" },
    # { key = "F2", mods = "Shift", chars = "\u001B[1;2Q" },
    # { key = "F3", mods = "Shift", chars = "\u001B[1;2R" },
    # { key = "F4", mods = "Shift", chars = "\u001B[1;2S" },
    # { key = "F5", mods = "Shift", chars = "\u001B[15;2~" },
    # { key = "F6", mods = "Shift", chars = "\u001B[17;2~" },
    # { key = "F7", mods = "Shift", chars = "\u001B[18;2~" },
    # { key = "F8", mods = "Shift", chars = "\u001B[19;2~" },
    # { key = "F9", mods = "Shift", chars = "\u001B[20;2~" },
    # { key = "F10", mods = "Shift", chars = "\u001B[21;2~" },
    # { key = "F11", mods = "Shift", chars = "\u001B[23;2~" },
    # { key = "F12", mods = "Shift", chars = "\u001B[24;2~" },
    # { key = "F1", mods = "Control", chars = "\u001B[1;5P" },
    # { key = "F2", mods = "Control", chars = "\u001B[1;5Q" },
    # { key = "F3", mods = "Control", chars = "\u001B[1;5R" },
    # { key = "F4", mods = "Control", chars = "\u001B[1;5S" },
    # { key = "F5", mods = "Control", chars = "\u001B[15;5~" },
    # { key = "F6", mods = "Control", chars = "\u001B[17;5~" },
    # { key = "F7", mods = "Control", chars = "\u001B[18;5~" },
    # { key = "F8", mods = "Control", chars = "\u001B[19;5~" },
    # { key = "F9", mods = "Control", chars = "\u001B[20;5~" },
    # { key = "F10", mods = "Control", chars = "\u001B[21;5~" },
    # { key = "F11", mods = "Control", chars = "\u001B[23;5~" },
    # { key = "F12", mods = "Control", chars = "\u001B[24;5~" },
    # { key = "F1", mods = "Alt", chars = "\u001B[1;6P" },
    # { key = "F2", mods = "Alt", chars = "\u001B[1;6Q" },
    # { key = "F3", mods = "Alt", chars = "\u001B[1;6R" },
    # { key = "F4", mods = "Alt", chars = "\u001B[1;6S" },
    # { key = "F5", mods = "Alt", chars = "\u001B[15;6~" },
    # { key = "F6", mods = "Alt", chars = "\u001B[17;6~" },
    # { key = "F7", mods = "Alt", chars = "\u001B[18;6~" },
    # { key = "F8", mods = "Alt", chars = "\u001B[19;6~" },
    # { key = "F9", mods = "Alt", chars = "\u001B[20;6~" },
    # { key = "F10", mods = "Alt", chars = "\u001B[21;6~" },
    # { key = "F11", mods = "Alt", chars = "\u001B[23;6~" },
    # { key = "F12", mods = "Alt", chars = "\u001B[24;6~" },
    # { key = "F1", mods = "Super", chars = "\u001B[1;3P" },
    # { key = "F2", mods = "Super", chars = "\u001B[1;3Q" },
    # { key = "F3", mods = "Super", chars = "\u001B[1;3R" },
    # { key = "F4", mods = "Super", chars = "\u001B[1;3S" },
    # { key = "F5", mods = "Super", chars = "\u001B[15;3~" },
    # { key = "F6", mods = "Super", chars = "\u001B[17;3~" },
    # { key = "F7", mods = "Super", chars = "\u001B[18;3~" },
    # { key = "F8", mods = "Super", chars = "\u001B[19;3~" },
    # { key = "F9", mods = "Super", chars = "\u001B[20;3~" },
    # { key = "F10", mods = "Super", chars = "\u001B[21;3~" },
    # { key = "F11", mods = "Super", chars = "\u001B[23;3~" },
    # { key = "F12", mods = "Super", chars = "\u001B[24;3~" },
    # { chars = """
    # """, key = "NumpadEnter" },
]
